services:
  # Web Service (Django)
  - type: web
    name: booklog-app
    runtime: python
    region: oregon # or singapore, frankfurt
    rootDir: backend
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: booklog-db-postgres # データベース名を変更
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.11.4

  # Database (PostgreSQL)
  - type: psql # mysqlからpsqlに変更
    name: booklog-db-postgres # サービス名を変更
    region: oregon # Webサービスと同じリージョンを推奨
    plan: free
    # PostgreSQLのバージョンを指定 (例)
    # postgresqlVersion: 15