services:
  - type: web
    name: booklog-app
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: booklog-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "booklog-app.onrender.com,localhost,127.0.0.1"

databases:
  - name: booklog-db
    databaseName: booklog_db
    user: booklog_user
