# Generated by Django 5.2.3 on 2025-06-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(blank=True, null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='content',
            field=models.TextField(verbose_name='memo'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='memo_date'),
        ),
    ]
